-- Automatically generated by bindings.c. DO NOT EDIT.

local ffi = require("ffi")
ffi.cdef[[
void* Joystick_new(int port);
double Joystick_GetX(void* _this);
double Joystick_GetY(void* _this);
bool Joystick_GetRawButton(void* _this, int button);
bool Joystick_GetRawButtonPressed(void* _this, int button);
bool Joystick_GetRawButtonReleased(void* _this, int button);
double Joystick_GetRawAxis(void* _this, int axis);
void* PWMSparkMax_new(int channel);
void* PWMSparkMax_toSpeedController(void* _this);
void PWMSparkMax_Set(void* _this, double value);
void* TalonSRX_new(int deviceNumber);
void* TalonSRX_toSpeedController(void* _this);
double TalonSRX_Get(void* _this);
void TalonSRX_Set(void* _this, double value);
void TalonSRX_SetInverted(void* _this, int invertType);
void* TalonFX_new(int deviceNumber);
void* TalonFX_toSpeedController(void* _this);
double TalonFX_Get(void* _this);
void TalonFX_Set(void* _this, double value);
void TalonFX_SetInverted(void* _this, int invertType);
void* DifferentialDrive_new(void* leftMotor, void* rightMotor);
void DifferentialDrive_ArcadeDrive(void* _this, double xSpeed, double zRotation, bool squareInputs);
void* DoubleSolenoid_new(int forwardChannel, int reverseChannel);
double GetFPGATimestamp();
]]
