-- Automatically generated by bindings.c. DO NOT EDIT.

local ffi = require("ffi")
ffi.cdef[[
void* Joystick_new(int port);
double Joystick_GetX(void* _this);
double Joystick_GetY(void* _this);
bool Joystick_GetRawButton(void* _this, int button);
bool Joystick_GetRawButtonPressed(void* _this, int button);
bool Joystick_GetRawButtonReleased(void* _this, int button);
double Joystick_GetRawAxis(void* _this, int axis);
]]
