// Automatically generated by bindings.c. DO NOT EDIT.

#include <frc/Joystick.h>

#include "luadef.h"

LUAFUNC void* Joystick_new(void* _m, int port) {
    return new frc::Joystick(port);
}

LUAFUNC double Joystick_GetX(void* _m) {
    return ((frc::Joystick*)_m)->GetX();
}

LUAFUNC double Joystick_GetY(void* _m) {
    return ((frc::Joystick*)_m)->GetY();
}

