// Automatically generated by bindings.c. DO NOT EDIT.

#include <frc/Joystick.h>

#include "luadef.h"

LUAFUNC void* Joystick_new(int port) {
}

LUAFUNC double Joystick_GetX() {
}

LUAFUNC double Joystick_GetY() {
}

