// Automatically generated by bindings.c. DO NOT EDIT.

#include <ctre/phoenix/motorcontrol/can/WPI_TalonFX.h>
#include <ctre/phoenix/motorcontrol/can/WPI_TalonSRX.h>
#include <frc/PWMSparkMax.h>
#include <frc/TimedRobot.h>
#include <frc/drive/DifferentialDrive.h>

#include "luadef.h"

LUAFUNC void* PWMSparkMax_new(void* _m, int channel) {
    return new frc::PWMSparkMax(channel);
}

LUAFUNC void* PWMSparkMax_toSpeedController(void* _m) {
    frc::SpeedController* _converted = (frc::PWMSparkMax*)_m;
    return _converted;
}

LUAFUNC void PWMSparkMax_Set(void* _m, double value) {
    return ((frc::PWMSparkMax*)_m)
        ->Set(value);
}

LUAFUNC void* TalonSRX_new(void* _m, int deviceNumber) {
    return new ctre::phoenix::motorcontrol::can::WPI_TalonSRX(deviceNumber);
}

LUAFUNC void* TalonSRX_toSpeedController(void* _m) {
    frc::SpeedController* _converted = (ctre::phoenix::motorcontrol::can::WPI_TalonSRX*)_m;
    return _converted;
}

LUAFUNC double TalonSRX_Get(void* _m) {
    return ((ctre::phoenix::motorcontrol::can::WPI_TalonSRX*)_m)
        ->Get();
}

LUAFUNC void TalonSRX_Set(void* _m, double value) {
    return ((ctre::phoenix::motorcontrol::can::WPI_TalonSRX*)_m)
        ->Set(value);
}

LUAFUNC void TalonSRX_SetInverted(void* _m, int invertType) {
    return ((ctre::phoenix::motorcontrol::can::WPI_TalonSRX*)_m)
        ->SetInverted((ctre::phoenix::motorcontrol::InvertType)invertType);
}

LUAFUNC void* TalonFX_new(void* _m, int deviceNumber) {
    return new ctre::phoenix::motorcontrol::can::WPI_TalonFX(deviceNumber);
}

LUAFUNC void* TalonFX_toSpeedController(void* _m) {
    frc::SpeedController* _converted = (ctre::phoenix::motorcontrol::can::WPI_TalonFX*)_m;
    return _converted;
}

LUAFUNC double TalonFX_Get(void* _m) {
    return ((ctre::phoenix::motorcontrol::can::WPI_TalonFX*)_m)
        ->Get();
}

LUAFUNC void TalonFX_Set(void* _m, double value) {
    return ((ctre::phoenix::motorcontrol::can::WPI_TalonFX*)_m)
        ->Set(value);
}

LUAFUNC void TalonFX_SetInverted(void* _m, int invertType) {
    return ((ctre::phoenix::motorcontrol::can::WPI_TalonFX*)_m)
        ->SetInverted((ctre::phoenix::motorcontrol::InvertType)invertType);
}

LUAFUNC void* DifferentialDrive_new(void* _m, void* leftMotor, void* rightMotor) {

      auto l = (frc::SpeedController*)leftMotor;
      auto r = (frc::SpeedController*)rightMotor;
      return new frc::DifferentialDrive(*l, *r);
    
}

LUAFUNC void DifferentialDrive_ArcadeDrive(void* _m, double xSpeed, double zRotation, bool squareInputs) {
    return ((frc::DifferentialDrive*)_m)
        ->ArcadeDrive(xSpeed, zRotation, squareInputs);
}
