// Automatically generated by bindings.c. DO NOT EDIT.

#include <ctre/phoenix/motorcontrol/can/WPI_TalonFX.h>
#include <ctre/phoenix/motorcontrol/can/WPI_TalonSRX.h>
#include <frc/PWMSparkMax.h>
#include <frc/TimedRobot.h>
#include <frc/drive/DifferentialDrive.h>

#include "luadef.h"

LUAFUNC void* PWMSparkMax_new(void* _m, int channel) {
}

