// Automatically generated by bindings.c. DO NOT EDIT.

#include <frc/Solenoid.h>
#include <frc/DoubleSolenoid.h>

#include "luadef.h"

LUAFUNC void* DoubleSolenoid_new(void* _m, int forwardChannel, int reverseChannel) {
}

LUAFUNC void DoubleSolenoid_Set(void* _m) {
}

