// Automatically generated by bindings.c. DO NOT EDIT.

#include <frc/Timer.h>

#include "luadef.h"

LUAFUNC double GetFPGATimestamp(void* _m) {

    return frc::Timer::GetFPGATimestamp();
  
}
