// Automatically generated by bindings.c. DO NOT EDIT.

#include <frc/SPI.h>
#include "AHRS.h"

#include "luadef.h"

LUAFUNC void* AHRS_new(int value) {
    return new AHRS((frc::SPI::Port)value);
}

LUAFUNC float AHRS_GetPitch(void* _this) {
    auto _result = ((AHRS*)_this)
        ->GetPitch();
    return _result;
}

LUAFUNC void AHRS_Reset(void* _this) {
    ((AHRS*)_this)
        ->Reset();
}
