// Automatically generated by bindings.c. DO NOT EDIT.

#include <frc/Joystick.h>

#include "luadef.h"

LUAFUNC void* Joystick_new(int port) {
    return new frc::Joystick(port);
}

LUAFUNC double Joystick_GetX(void* _this) {
    return ((frc::Joystick*)_this)
        ->GetX();
}

LUAFUNC double Joystick_GetY(void* _this) {
    return ((frc::Joystick*)_this)
        ->GetY();
}

LUAFUNC bool Joystick_GetRawButton(void* _this, int button) {
    return ((frc::Joystick*)_this)
        ->GetRawButton(button);
}

LUAFUNC bool Joystick_GetRawButtonPressed(void* _this, int button) {
    return ((frc::Joystick*)_this)
        ->GetRawButtonPressed(button);
}

LUAFUNC bool Joystick_GetRawButtonReleased(void* _this, int button) {
    return ((frc::Joystick*)_this)
        ->GetRawButtonReleased(button);
}

LUAFUNC double Joystick_GetRawAxis(void* _this, int axis) {
    return ((frc::Joystick*)_this)
        ->GetRawAxis(axis);
}
