// Automatically generated by bindings.c. DO NOT EDIT.

#include <frc/Solenoid.h>
#include <frc/DoubleSolenoid.h>

#include "luadef.h"

LUAFUNC void* DoubleSolenoid_new(int forwardChannel, int reverseChannel) {
    return new frc::DoubleSolenoid(forwardChannel, reverseChannel);
}
